mithorium-common: Drop system sided location blobs
They're not too much useful anyway, and giving this error on Android 12.1:

E AndroidRuntime: FATAL EXCEPTION: IZatServiceContext
E AndroidRuntime: Process: com.qualcomm.location, PID: 3180
E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qualcomm/location/izatprovider/NpProxy$LocationController;
E AndroidRuntime: 	at com.qualcomm.location.izatprovider.NpProxy.initServiceBinding(NpProxy.java:126)
E AndroidRuntime: 	at com.qualcomm.location.izatprovider.NpProxy.handleMessage(NpProxy.java:257)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.qualcomm.location.izatprovider.NpProxy$LocationController
E AndroidRuntime: 	... 6 more
W RescueParty: Attempting rescue level FACTORY_RESET